### ISSUE TITLE
I dont see colors etc...

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#1]
Hello i have issue

i dont see colors styles etc.... i only see it on /wp-admin/customize.php?

you look on this screenshots please

https://postimg.org/image/bzc58549r/

https://postimg.org/image/6p76guk0v/

**Comment by buddycore** [comment]
Hello, if you activate the theme and head into wp-admin > appearance > customize > theme decor > logo and colours > choose colour

You can change the colours in the theme.

**Comment by inzerat** [comment]
Yes resolved
