### ISSUE TITLE
If i compose message, it can be with whisperer for To (username)

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#10]
If i compose message, it can be with whisperer for To (username)

**Comment by buddycore** [comment]
I don't know what you are trying to achieve here, could you explain more please?

**Comment by inzerat** [comment]
I am sorry for my English. I attach the image of wireframe...
![untitled3](https://cloud.githubusercontent.com/assets/21200726/18201639/a93a26d2-710b-11e6-9d78-48dee9b004cd.png)

**Comment by buddycore** [comment]
I have added support for this now, however I am unable to get full control of the style. If you have any suggestions how to position this next to the "To (Username)" field I will follow your guide.
