### ISSUE TITLE
Link on compose message on profile of other users

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#11]
I want to write a message to someone and look at his profile, it would be good button or link on this possibility with the completed message recipients

**Comment by buddycore** [comment]
You can visit a member profile by clicking their avatar or username in a message thread.

**Comment by inzerat** [comment]
Sorry, you do not understand how I wrote it. I attach the wireframe...
![untitled2](https://cloud.githubusercontent.com/assets/21200726/18201464/a948d444-710a-11e6-9134-d54f8845c3b5.png)

**Comment by buddycore** [comment]
This has been added.
