### ISSUE TITLE
The message icon in the header, including displaying the number of new messages

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#12]
The message icon in the header, including displaying the number of new messages
like this: 
![untitled](https://cloud.githubusercontent.com/assets/21200726/18156573/68b71952-7017-11e6-988b-d279336220cd.png)

**Comment by buddycore** [comment]
There is a notification count in the header which has all notifications (including messages). I see why you would want this however in order to maintain the themes responsive ability this hasn't been added.

You could add this yourself but personally I wouldn't.

**Comment by inzerat** [comment]
I think one icon does not prevent responsivity. Notification messages are definitely the most important element on every social network.
