### ISSUE TITLE
Extension is active

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#13]
There is a bug. For example if you don't enable friendships option in buddypress it will break the layout because you don't do a check to see if it is active or not.

This also also happens in activity feed if you don't have groups active. The filtering select options will break the layout.

**Comment by buddycore** [comment]
Thanks Wemago I will look into this, I check in other areas of the theme for these components but I've missed a few things. 

I'll make the changes and update this ticket asap.

**Comment by buddycore** [comment]
I've made some updates to member header area, the group header area and also activity stream should now be working with these options. Updates to the master branch.

**Comment by Wemago** [comment]
That's what I call great work! :+1: 
I'll test in a sec.

**Comment by buddycore** [comment]
Let me know how you get on.

**Comment by Wemago** [comment]
Its working but now you have some css problems. When you deactivate extended profiles you'll have the data and links in the wrong location.

**Comment by buddycore** [comment]
Yes this should work now. If you really need an alternative header area for when cover images are switched off let me know.

I've pushed again to master branch
