### ISSUE TITLE
Mobile Menu Improvement

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#18]
Just a small improvement for mobile menu, I would remove border and background for menu title, making it to look cleaner then the current one.

**Comment by buddycore** [comment]
Agreed! I've placed an alternate style now.

**Comment by Wemago** [comment]
Just notice something, if you have a lot of sub child for menu links then the menu will get really big and in mobile that's really bad. I would use some kind of accordion menu or something like that.

**Comment by buddycore** [comment]
I think it's ok for now. Depends how people use the theme and currently there's not enough people to say either way.
