### ISSUE TITLE
Small Header Improvements

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#19]
Sorry for so many issues, but I truly believe in the success of this theme, in so many ways.

These are just small visual header improvements that I think it fits perfectly in your theme.
1. Sticky Header
2. Any logo uploaded should be resized to the height of the menu, this way it wont break the visual side.

**Comment by buddycore** [comment]
Thanks, I can agree with the sticky header. I've enabled this for larger resolutions.
*edit, I'm going to make this into an option via the customizer.

The logo, also I agree but I could be here all day playing with that to crop an image for the logo. A user should take time to prepare a logo that fits the site in that location. It's not much to ask in this case.

You can get the fixed header update from the master branch now and thanks for your feedback.

**Comment by Wemago** [comment]
I agree with you, user could just upload the correct logo size, but wouldn't be easy just using wp default image size option(add_image_size())? I'll try later something if you like it I'll do a pull request.

**Comment by buddycore** [comment]
*edit - Sticky header is now an option via the theme customizer, it's under the layout panel.

I guess but the cropping might not always happen in the correct location. I think it's more trouble than its worth. 

Pull requests are fine, I'm new to GitHub and it's all a learning process.
