### ISSUE TITLE
In members loop is always 75 updates

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#2]
this is error or missing func? https://snag.gy/doYrRK.jpg

**Comment by buddycore** [comment]
Yes, I need to fix that. I'll get to that later today.

**Comment by buddycore** [comment]
You can get the latest master branch for this functionality, it's been included in both the members loop and friendship loop. Where you use those template files you will get this output.

**Comment by inzerat** [comment]
Yes thank you resolved
