### ISSUE TITLE
Navigation Parent Selected

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#20]
Another improvement and this is one of the things I think that most themes in wordpress break. 

When you go to a child page, normal or buddypress, parent link doesn't have css active or selected connected to it.

Using your website for example
Pages > Sidebar Left   - Main menu pages link should be active/selected
Members > buddycore   - Again main menu link should be active/selected and its not

**Comment by buddycore** [comment]
Yeah I know what you mean, It gets a little complicated with selecting parents from child selectors and what not.

I'll leave this as is for now until there is more people asking but thanks for making the ticket.

**Comment by Wemago** [comment]
From twenty twelve theme

`.main-navigation .current-menu-item > a,
    .main-navigation .current-menu-ancestor > a,
    .main-navigation .current_page_item > a,
    .main-navigation .current_page_ancestor > a {
        color: #636363;
        font-weight: bold;
    }`
