### ISSUE TITLE
To post in an open group without joining it.

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#22]
I want to know whether it is possible to post in a group(open group) without joining the group..like we can read the post of the open group.

i find this https://buddypress.org/support/topic/members-cant-post-to-groups-that-they-didnt-join-why/ but this is 6 years old

**Comment by buddycore** [comment]
Hmm yeah this is more for the BuddyPress forums I think. Groups have their own conditions to be met and aren't included in the @activity mention system that's more specifically for user filtering.

I'm sure you could add this, but try the BuddyPress forums first.

**Comment by inzerat** [comment]
Comment on buddypress: "f you post in a Public Group that you aren’t a member of, then you are automatically added to the Group. I believe the only exception for this is site administrators."

https://buddypress.org/support/topic/to-post-in-an-open-group-without-joining-it-2/#post-258561

**Comment by buddycore** [comment]
Great.

**Comment by inzerat** [comment]
Great what? :-) I understand it well that when the post-form to the public for each group, users can add comments and thus become a member of the group? You edit template and add a post-form to non-members? (but are logged in of course)
