### ISSUE TITLE
User Experience for mobile resolution

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#24]
I see a big problem in control on mobile. Profile photo (number 1) would not do such a link but should have the same functionality as the (number 2). Because users often clicked elsewhere. Link to profile are in the select box, so why giving twice?

(Point 3) would completely abolished. Users do not know what the control panel and what is just a selection of text pages. I think that for the purposes of social networks have no need to select text pages.

And of course our usual theme, notification messages. The most important thing for most users - communication.

![untitled](https://cloud.githubusercontent.com/assets/21200726/18426363/5a8acee8-78c1-11e6-8585-ad9dc353798c.png)

**Comment by buddycore** [comment]
Page navigation must be present, if you don't want this link remove it from the theme files. 

Profile link, the image is a direct link to a user profile. It's not complicated.

Notifications show if you have any as a bubble.

I need to spend a little more time thinking about options available as administrator of site using this theme. In future versions I might make an option for this navigation.
