### ISSUE TITLE
On the profile page, it's wrong shows the number of groups

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#25]
I'm on a user's profile page. The user is not added in any group. But it shows that it is added in 11 groups. (Which is the total current number on my website.) This is bug.

**Comment by buddycore** [comment]
Let me look into this a little later today.

**Comment by buddycore** [comment]
A little later than planned this has been updated in 2 areas.

1) BuddyPress user nav drop down
2) Member profiles header area

Hope that helps.
