### ISSUE TITLE
Optimalization styles for buddypress activity plus

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#27]
This plugin is for upload photos, but if i activated him, styles are not corectly

https://cs.wordpress.org/plugins/buddypress-activity-plus/

**Comment by buddycore** [comment]
I will download a test for this plugin and try to figure it out. I don't mind a plugin like this it helps us with activity media.

**Comment by buddycore** [comment]
Support has now been added, although I have only tested this inside of Chrome.

**Comment by inzerat** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21200726/18616581/c0b3ae72-7dbe-11e6-82d1-67dac8dfdfef.png)

**Comment by buddycore** [comment]
I changed the icon and tidied up some CSS. 

You can change the thumbnail sizes via the plugin settings.

**Comment by inzerat** [comment]
Hello thank you but icon are not styll ok. Better is icon of photoaparat as have facebook: http://cdn-4.askdavetaylor.com/wp-content/uploads/2014/12/add-pic-photo-facebook-update-1.png

**Comment by buddycore** [comment]
It's now a camera for image uploads just like Facebook. There are limits currently as to what I can do with this plugin in terms of layout. So we have a working implementation now. 

If you find any problems cross browser let me know.
