### ISSUE TITLE
Indications received messages

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#28]
I write someone a message and want to know whether you read it. For example, "Sean 5:20" Like on Facebook.

![facebookseenimage](https://cloud.githubusercontent.com/assets/21200726/18722718/0f6cea3c-8036-11e6-8ec6-d89741149621.png)

**Comment by buddycore** [comment]
Nice idea actually, I can apply this into private messaging... There isn't a chat feature atm with Surface.

I will make this a theme option. It really should be a BuddyPress option but my skills are limited at the moment.

**Comment by buddycore** [comment]
This has also been added. I may make this an option for the theme at a later date.

It works like this, if you are sender it will show in the thread, next to the message when a message has been seen or not seen by the recipient.

That's all.

*edit - also, this will not work on old messages. It will show inaccurate readings.
