### ISSUE TITLE
Better detail page of activity

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#29]
My idea is add profile header like this:

![untitled](https://cloud.githubusercontent.com/assets/21200726/18826947/5b28523e-83d0-11e6-9397-de978c5e29c6.png)

**Comment by buddycore** [comment]
So you want to have a member profile header on single activity pages?

**Comment by inzerat** [comment]
Yes but on screenshot is mistake, correct must be profile header of omobatv1 user

**Comment by buddycore** [comment]
i'll get onto this on Sunday, have a few other things going on this week. I see what you mean. Profile header to match the original poster.

**Comment by buddycore** [comment]
Now added.
