### ISSUE TITLE
Searching in activity

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#3]
Hello, you can do search function in activity as part of template?

**Comment by buddycore** [comment]
If you can show me a guide to make that happen I'll try to get that included.

**Comment by inzerat** [comment]
Hello thank you, maybe this https://buddydev.com/buddypress/making-buddypress-activity-searchable/ ?

**Comment by inzerat** [comment]
Hey sorry this is bad idea because if will 1 000 000 activity post search will be slow.... Facebook Twitter etc this is not support too...i close it
