### ISSUE TITLE
Important update for better UI communication

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#30]
1) Add a message icon. On mobile, it is the most important thing for new users. The icon is there a cool fit for smaller resolution!

2) And adding to an earlier issue: For https://github.com/buddycore/surface-theme/issues/7 - Please do it also sent messages folder

![untitled](https://cloud.githubusercontent.com/assets/21200726/18986431/04b91db8-86fd-11e6-848f-5bd911c763a9.png)

**Comment by buddycore** [comment]
This has been added, and a minimum requirement overlay has been added for devices with resolution smaller than 300px in width.

**Comment by inzerat** [comment]
1) better is if message icon is displayed always - not only if is unread

**Comment by buddycore** [comment]
I will make it an option which you can enable or disable with your setup.

*edit, this is now an option and will show always if setting is checked. Otherwise it wont show at all.
