### ISSUE TITLE
Buddypress activity plus doesnt work correct without login

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#32]
Hi, i have one issue, activity plus doesnt work correct if click on image thumbnail and i want popup image. This issue is only if i not login.

**Comment by buddycore** [comment]
You must be logged in to post anything to the activity stream.

*edit - I see this problem now, I think this is more for BP Activity Plus support. Strange bug. 

The only one that really bothers me at the moment is the sidebar layout getting messed up when using WP-admin customizer.
