### ISSUE TITLE
Display number of new messages

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#34]
The icon message must show the number of new messages. Like a: https://cloud.githubusercontent.com/assets/21200726/18426363/5a8acee8-78c1-11e6-8585-ad9dc353798c.png

**Comment by buddycore** [comment]
Ok this has been modified, if you want to modify this further you can edit the .scss files to create your own style. Also remember, this is an option and can be activated with WordPress Theme Customizer
