### ISSUE TITLE
Why do not work popup of image (activity plus) if i am not login?

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#37]
Why do not work popup of image (activity plus) if i am not login?

Look in Twig (URL you have via email)

**Comment by buddycore** [comment]
Yes, I see this. I will investigate a little bit later. This is a problem. It's probably a script conflict somewhere.

**Comment by buddycore** [comment]
Might come back to this.

**Comment by buddycore** [comment]
I have this problem also on my installation. For now I'm going to close this issue as my main aim is to build a theme and later support for other plugins.
