### ISSUE TITLE
Confirm message on delete

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#38]
When deleting something there should be a message asking to confirm the action.
If you click by mistake delete you will lose your post/comment for good.

**Comment by buddycore** [comment]
The confirm message will appear on content added AFTER a page refresh. Try this and get back to me if problem persists as I cannot replicate the issue.

**Comment by Wemago** [comment]
Just tried in your website...Published status, clicked delete and no message asking me to confirm deletion. It should ask me before performing action.

**Comment by buddycore** [comment]
Yes, you need to refresh the page.

**Comment by Wemago** [comment]
Ok after refreshing it worked, but imagine you have a user that publishes something and doesn't refresh the page, they scroll down and by mistake click delete. They will lose the clicked publication forever. We should prevent that.

**Comment by buddycore** [comment]
I know I understand your problem, I will keep this ticket open, if others want this I'll look to do that.

It's worth mentioning that there are benefits of not binding the confirmation without a page load. Maybe you can think about this and see those also from a UX perspective.

**Comment by buddycore** [comment]
I'm going to close this ticket Been open for a while and no other replies. Feel free to open it again another time.
