### ISSUE TITLE
Activity plus add link

### ISSUE THREAD

**Issue by Wemago** [buddycore/surface-theme#39]
When publishing a link using activity plus after submission doesn't show anything.

**Comment by buddycore** [comment]
This works on my install, I tried pasting a YouTube link and then clicking "add link" it works as expected.

Also I notice when adding a link the layout isn't so nice, I will fix this.

**Comment by Wemago** [comment]
I tried in your website using a github link and it doesn't publish

Copied the link to this github page, went to your website, share link, pasted there, appeared image and title, then clicked submit and it refreshes without publishing anything.

**Comment by buddycore** [comment]
I tested this also, again it works on my installation. Sometimes there are conflicts with plugins.

**Comment by Wemago** [comment]
I'm trying in your website buddycore.com not in a local installation. Tried different times already and two different browsers, could be a browser problem but it isn't.

BTW good work with this theme. Enjoying the direction its going.

**Comment by Wemago** [comment]
Ok tested again. Problem is when you have a thumbnail. Without thumbnail it publishes. Think it gets in conflict with something.

**Comment by buddycore** [comment]
As you can see I published one and a thumbnail was selected http://buddycore.com/m/buddycore/activity/160/

This is a BuddyPress Activity Plus issue, sometimes a thumbnail cannot be generated. You should ask them to help you provide a default.

**Comment by Wemago** [comment]
Strange. I'm not managing to do it.
http://buddycore.com/m/js83/

**Comment by buddycore** [comment]
Yes, I couldn't either for the templatic.com link provided. I could with this page https://templatic.com/app-plugins/import-facebook-events-directory-wordpress

Again, it's a BP Activity Plus problem.

**Comment by Wemago** [comment]
Later I'll try to figure some solution for this and I'll share it here.  Yea it most be activity plus

**Comment by buddycore** [comment]
Great, can I close this issue then?
