### ISSUE TITLE
Idea for better UX for motivation of change avatar

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#41]
Default avatar and link for change: http://www.buddycore.com/user/profile/change-avatar/ 

These two things put into Sidebar please.

**Comment by buddycore** [comment]
The sidebar needs a lot of work, do you have any other suggestions?

**Comment by inzerat** [comment]
Etc Buddypress members widget ( A dynamic list of recently active, popular, and newest members  )
I suggest you take inspiration from facebook sidebar - generally say it is necessary to somehow revive, because space sidebar looks empty

**Comment by buddycore** [comment]
Ok I am working on this.

I have uploaded a sample of what I am trying to achieve on my site. Also you can pull the latest commit here on GitHub to download the files.

The sidebar is not functional at the moment due to experimenting with this layout and features.

Could you take a look and tell me if you like this idea or not.

**Comment by buddycore** [comment]
This has been updated and sidebar is almost ready, there are some changes still to be commited but the general idea is there.

**Comment by inzerat** [comment]
Hello, thank you for changes. But i have idea for more helpful usage - UX.
![untitled](https://cloud.githubusercontent.com/assets/21200726/19431408/aa49bb26-9458-11e6-8155-64ae2f3f9c87.png)

**Comment by buddycore** [comment]
I still need to make some more work in the sidebar area. Making suggestions for users to become friends with others is already present. There is a list of new members, popular members, active members and even online members in the sidebar. You could add some text to these areas which will say "Why not become friends with these members?" and the same for Groups.

**Comment by inzerat** [comment]
I closed this issues for now. I will in future better ideas for this issuse.. (wireframes)
