### ISSUE TITLE
Share for activities

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#42]
Inspiration: https://publish.twitter.com/

**Comment by buddycore** [comment]
I don't know what you mean

**Comment by inzerat** [comment]
etc https://hc.weebly.com/hc/en-us/article_attachments/203583357/youtube_share.png

**Comment by buddycore** [comment]
You want a link to share activity? Just copy the url

**Comment by inzerat** [comment]
Not only. Real problem is share button for activity, embed code atd...
embed code for twitter:
`<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sunsets don&#39;t get much better than this one over <a href="https://twitter.com/GrandTetonNPS">@GrandTetonNPS</a>. <a href="https://twitter.com/hashtag/nature?src=hash">#nature</a> <a href="https://twitter.com/hashtag/sunset?src=hash">#sunset</a> <a href="http://t.co/YuKy2rcjyU">pic.twitter.com/YuKy2rcjyU</a></p>&mdash; US Dept of Interior (@Interior) <a href="https://twitter.com/Interior/status/463440424141459456">May 5, 2014</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by buddycore** [comment]
I still do not know what you mean.

Please tell me in words, what you are trying to achieve.

**Comment by inzerat** [comment]
every social network have share options:

facebook: https://barrd.net/wp-content/uploads/Sharing-a-Post-on-Facebook-as-a-Page-Manager-share-option.jpg
youtube: http://pad2.whstatic.com/images/thumb/4/47/Post-a-YouTube-Video-on-Facebook-Step-3-Version-3.jpg/aid145837-728px-Post-a-YouTube-Video-on-Facebook-Step-3-Version-3.jpg
twitter: https://g.twimg.com/dev/documentation/image/embed-video-twitter-com.png

**Comment by buddycore** [comment]
Thank you for elaborating, here is my response.

WordPress allows your site to become an oEmbed provider you can do things like this http://buddycore.com/what-is-surface/embed/ and paste that link into areas supported like the editor.

You can also do this with BuddyPress activity items, but I've yet to see this working.

So, the options are provide a share link (which is basically just copying a url) or providing an embed link to places that support this.

Just because other sites have "embedding" for their content doesn't mean Surface should have that.

**Comment by inzerat** [comment]
Hi thank you for response. Functional version of http://buddycore.com/m/buddycore/activity/177/embed/ would be great.

**Comment by buddycore** [comment]
Yes, I can't make this work for now and also it's maybe better as a plugin.

You may want to raise this on the http://buddypress.org/support forums for a solution.

**Comment by inzerat** [comment]
This was added in BuddyPress 2.6. See https://codex.buddypress.org/activity-embeds/.

**Comment by buddycore** [comment]
Yes, this only works when adding content to the editor when creating a post from wp-admin. It's not something that works when posting an activity update. You can maybe understand why.
