### ISSUE TITLE
Better header notifications are important!

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#43]
Hello,

Icon for messaging and notification be done better, see screenshot and instructions. Very please, do it, it will look better.

here is tutorial: http://jsfiddle.net/rahilsondhi/FdmHf/4/
a discussion: http://stackoverflow.com/questions/5747863/easiest-css-for-facebook-style-red-notifications

![untitled](https://cloud.githubusercontent.com/assets/21200726/19559034/f4e27f5c-96cd-11e6-8a19-aa0fd3467c6e.png)

**Comment by buddycore** [comment]
This has been added.
