### ISSUE TITLE
Update header notifications

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#44]
For: https://github.com/buddycore/surface-theme/issues/43

Great work! This is look prety good!

One new improvements: If 0 unread messages, both icons should be displayed.

**Comment by buddycore** [comment]
I think this is fine as it is. I may change the icon for messages to use FontAwesome but apart from that it works as intended. BuddyPress is not Facebook, although I understand your efforts to make it like this. 

We have to accept the differences between both platforms.

It makes sense to not show these icons when there are no notifications or messages, it frees up space and means when notifications are present a user has a better chance to see them.
