### ISSUE TITLE
Display icons for messaging and notification even if the number is 0

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#48]
I'll tell you why.
1) It looks better
2) It's faster access
3) The site looks more dynamic
4) eliminates the need to have links in the panel and it will be clearer

![untitled2](https://cloud.githubusercontent.com/assets/21200726/19636880/37d2fc50-99cc-11e6-882a-01b107285c7d.png)

**Comment by buddycore** [comment]
Number 4 is a good enough reason to me, so I will make this happen.

**Comment by buddycore** [comment]
This has now been implemented to the master branch, I will remove the option via customizer as this is now part of the default functionality.
