### ISSUE TITLE
Bugs in notifications

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#49]
1 ) mark as read, mark as unread
2) pagination crash layout

![notifikace](https://cloud.githubusercontent.com/assets/21200726/19703597/b0613338-9b04-11e6-9f2b-c25b8c60f15d.png)

**Comment by buddycore** [comment]
I've fixed  the pagination styles.

The reason it is "read" and "unread" is to make sure the layout doesn't break in mobile.
