### ISSUE TITLE
Icon for "REPLY"

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#50]
![untitled](https://cloud.githubusercontent.com/assets/21200726/19761293/8a152a2c-9c35-11e6-8314-c08bf92c88ef.png)

**Comment by inzerat** [comment]
Plus change text "reply" on "comments"... it is obviously better for the user and the more it will motivate

**Comment by inzerat** [comment]
And text "Favorite" change on "Save to favorites"

**Comment by buddycore** [comment]
The text will not change, if you wish to change the text for your theme you can edit the files directly.

Unless I've made a spelling mistake.

**Comment by inzerat** [comment]
And icon for comments?

**Comment by buddycore** [comment]
I still don't know what you want me to do with the icon

**Comment by inzerat** [comment]
Add icon for reply (https://cloud.githubusercontent.com/assets/21200726/19761293/8a152a2c-9c35-11e6-8314-c08bf92c88ef.png)

**Comment by buddycore** [comment]
I get you now, will update this tonight.
