### ISSUE TITLE
Add support for rtmedia

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#51]
https://en.wordpress.org/plugins/buddypress-media/

**Comment by buddycore** [comment]
What's wrong with BuddyPress Activity Plus? We've got support for that now.

**Comment by inzerat** [comment]
rtmedia have: albums, photo, audio/video upload, privacy, sharing, front-end uploads & more. All this works on mobile/tablets devices.

**Comment by buddycore** [comment]
So if we support RTMedia you will no longer be needing BP Activity Plus

**Comment by inzerat** [comment]
I think it might be a better solution, due to better support for mobile devices

**Comment by inzerat** [comment]
and videos etc. etc.

**Comment by buddycore** [comment]
I will investigate when I get some free time, currently I'm pretty busy.

**Comment by buddycore** [comment]
If you would like this support integrated you can email me with a job offer.
