### ISSUE TITLE
Make a select box for clarity UI

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#52]
It's a lot of places and it will be clearer

![untitled2](https://cloud.githubusercontent.com/assets/21200726/19962038/10013682-a1b6-11e6-8102-7729328b499b.png)

**Comment by buddycore** [comment]
Ok, I will look at this.

**Comment by buddycore** [comment]
This has been added now, if you wish to modify further you can edit the javascript file and also the css.
