### ISSUE TITLE
Bug in comments

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#53]
missing reply link on comment 554

http://www.ont***.com/wolf/activity/537/?nid=144#acomment-554

![untitled](https://cloud.githubusercontent.com/assets/21200726/20050717/2f90554c-a4cb-11e6-94eb-ffadc9770f03.png)

**Comment by buddycore** [comment]
Some items you cannot reply to. Looks like that's a threaded discussion, you can only reply to so many levels. This isn't something that is a "bug" it's the way BuddyPress works.
