### ISSUE TITLE
Idea for better UI of messages

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#55]
![untitled](https://cloud.githubusercontent.com/assets/21200726/20100459/dfa13774-a5bd-11e6-9d58-2871080cad41.png)

inspired by fb:
![851594_557571097654524_736649573_n](https://cloud.githubusercontent.com/assets/21200726/20100481/fb102e84-a5bd-11e6-8a38-b6e1efb90913.jpg)

**Comment by buddycore** [comment]
This is neat, although the problem I have is keeping this responsive. The goals for this theme are to make a fully mobile, tablet and desktop ready theme whilst utilising core features of WordPress and BuddyPress.

I'm not sure how this could be mobile ready, I like it and will give it some more thought.

I've been working on another theme for the past couple of weeks and haven't been able to give Surface much love.

**Comment by inzerat** [comment]
I have idea for responsive. After click on message - detail of corvesation open as a popup?

**Comment by buddycore** [comment]
The theme is a solid theme which delivers the functionality of BuddyPress and WordPress. 

For custom work you can email me with a job proposal and we may be able to work together but for things outside the scope of the project I'd need to charge for these things.

Thanks.
