### ISSUE TITLE
How change link on default avatar?

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#58]
I do not want default avatar from gravatar.com - how can i change this? It will be beter for optimalization of sped, every external source is slow for load of website. I recommanded change this for official theme too.

**Comment by buddycore** [comment]
I will make this as an option for you to enable inside of theme customizer.

**Comment by buddycore** [comment]
This has been added you can access it via theme customizer under the buddypress section and members component. 

Check the box to use a local default avatar over gravatar.

If you want to use a custom image for members default avatar, you can create one and place it inside the theme at this location with the name of member.png

`surface/asset/img/default/member.png` <--- just over write that file with your own.
