### ISSUE TITLE
Image upload on new update activity 

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#6]
Hello, Image upload on new update activity  without plugin, wow it was cool

**Comment by buddycore** [comment]
I tried to build this feature but ran into some problems which I was unable to figure out.

If this theme gets used I'll return to things like this and make sure it gets added. 

Would be nice for default functionality I agree and also choosing which file types are supported.

Activity streams can be a bit bland when only text or oembed is available.

**Comment by inzerat** [comment]
I might be a little sponsoring, what's your email?

**Comment by buddycore** [comment]
You can get me on this social [at] my domain . com

**Comment by inzerat** [comment]
----- The following addresses had permanent fatal errors -----
<social@buddycore.com>

  ----- Transcript of session follows -----
.. while talking to buddycore.com
>>> RCPT To:<social@buddycore.com>
<<< 550-JunkMail rejected - smtp.sa***a.c* (icewarp.sa***a.c*) [8****1]:47000
550 is in an RBL, see

**Comment by buddycore** [comment]
Yeah I'm using a crappy host, sorry about that. What's your email?... and I will send you one from my gmail.

**Comment by inzerat** [comment]
info@inzerat.top

**Comment by buddycore** [comment]
I've sent you an email now and removed the other posts here.
