### ISSUE TITLE
Icons for message UI

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#60]
In header of messages - menu:

Inbox - http://fontawesome.io/icon/inbox/
Starred - http://fontawesome.io/icon/star/
Sent - http://fontawesome.io/icon/paper-plane-o/
Compose - http://fontawesome.io/icon/pencil-square-o/

http://fontawesome.io/icons/

**Comment by buddycore** [comment]
I've modified this to include those icon suggestions, if you wish to modify this further you can edit the css files.
