### ISSUE TITLE
When upload profile image to group UX issue

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#66]
When you create a group in the first step, there is too see a button to upload, which is confusing and not necessary in the first step and is not working.

![untitled](https://cloud.githubusercontent.com/assets/21200726/20486411/ecb1ec32-afff-11e6-85c8-9d86dea6be84.png)

**Comment by buddycore** [comment]
I understand the problem you see here, however when a user has an avatar uploaded this "upload" link will also have "delete" available. 

For now, I wont change this functionality.
