### ISSUE TITLE
Messages - user image in inbox

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#7]
Maybe like a
![untitled](https://cloud.githubusercontent.com/assets/21200726/18009183/7600a9ea-6bab-11e6-8f11-f6289f5ec456.png)
:

???

**Comment by buddycore** [comment]
You can add this yourself with a small amount of editing. If you prefer me to add it I don't mind at all but I can't do it until Sunday now. Maybe tomorrow night.

**Comment by inzerat** [comment]
I think that's very good for the better user experience and UI. It would be valuable as well "message icon" in the header. For example, next to notifications warnings.

**Comment by buddycore** [comment]
This has now been added for the messages loop. I can add in other places also if required.

**Comment by inzerat** [comment]
Hello for sent messagess too please...

**Comment by buddycore** [comment]
The notification is to visit the message inbox, when there is one pending (marked as unread). It doesn't make sense to show this for messages sent.

When a user wants to see sent messages they can browse as normal.

No more on this issue please.
