### ISSUE TITLE
UX for filter box

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#75]
Please come back to this icon http://fontawesome.io/icon/filter/

and that it will do all resolutions, the bar is nice in responsive mode and too in desktop mode, look at the screenshot

![untitled](https://cloud.githubusercontent.com/assets/21200726/21099757/50d7131a-c070-11e6-898f-47173dac0f5c.png)

**Comment by buddycore** [comment]
Are you interested in my new theme? You can see it on my site, it's not finished yet but the ideas are there.
