### ISSUE TITLE
activity will be 2 post on row

### ISSUE THREAD

**Issue by inzerat** [buddycore/surface-theme#76]
![4591b71c-c089-11e6-9c2d-96a046496ac4](https://cloud.githubusercontent.com/assets/21200726/21306037/41c4d736-c5cf-11e6-8d1c-526e87bf186a.png)

**Comment by inzerat** [comment]
This is actual look: http://www.ontwig.com
This is actual style: http://www.ontwig.com/wp-content/themes/surface-theme-master/style.css

I need:
1. Posts breaks down at a mobile resolution
2. Gaps between the posts
3. When the post ends, others will just under

![serve php](https://cloud.githubusercontent.com/assets/21200726/21390023/f2d5c93e-c784-11e6-9d5f-4050a1461bcb.png)

**Comment by buddycore** [comment]
You will want to try something like this in your modified CSS.

`@media screen and (max-width: 750px) {
    ul#activity-stream li { width: 100% }
}`

**Comment by inzerat** [comment]
OK thank you very much.. It solves one point but what about the other two? Please help me

**Comment by buddycore** [comment]
You need to do something like

`ul#activity-stream li { margin-bottom: 20px; }`

**Comment by inzerat** [comment]
if you would look into style.css you'll find that this is already there and not working

**Comment by buddycore** [comment]
Ok, you will have to go into the following file.

`surface/buddypress/activity/entry.php`

Immediate after `<li class="<?php bp_activity_css_class(); ?>" id="activity-<?php bp_activity_id(); ?>">`

Add this `<div class="activity-container">`

Then go to the end of that file and just before `</li>` add `</div>'.

Basically you're adding a bit more markup. We have to style it a little bit differently.

Then you'll need to figure out what CSS to use. It will be something like this.

First you need to cancel out the original background color by doing...

`ul#activity-stream li { background-color: transparent; }`

Then add that to the new markup

`ul#activity-stream li div.activity-container { background-color: #FFF; padding: 20px; }

The padding will make the gaps you are looking for.

You will have to apply a negative margin though to the ul to fix it.

`ul#activity-stream { margin: -20px; }

But like I said you'll have to mess around with this for a while.

**Comment by inzerat** [comment]
here is result: http://www.ontwig.com/
Thank you, one last point - number 3 (When the post ends, others will just under)

**Comment by buddycore** [comment]
YW. For point number 3 you might want to use something like http://masonry.desandro.com/

**Comment by inzerat** [comment]
Is it any easiest solution?

**Comment by buddycore** [comment]
Probably you can do this with CSS and `float: left;` instead of `display: flex; flex-wrap: wrap;`

Happy Christmas
